name: lab1flut
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # ==== НАШИ ПАКЕТЫ ====
  get_it: ^7.6.0
  talker_flutter: ^3.4.0
  talker_dio_logger: ^2.0.0
  talker_bloc_logger: ^2.0.0

  go_router: ^13.0.0
  dio: ^5.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.0
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
